# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import posts_pb2 as posts__pb2


class PostServiceStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreatePost = channel.unary_unary(
        '/PostService/CreatePost',
        request_serializer=posts__pb2.PostRequest.SerializeToString,
        response_deserializer=posts__pb2.Post.FromString,
        )


class PostServiceServicer(object):

  def CreatePost(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PostServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreatePost': grpc.unary_unary_rpc_method_handler(
          servicer.CreatePost,
          request_deserializer=posts__pb2.PostRequest.FromString,
          response_serializer=posts__pb2.Post.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'PostService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
